export const EMPTY_ORDER_FORM = {
  allowManualPrice: false,
  canEditData: true,
  checkedInPickupPointId: null,
  clientPreferencesData: {
    locale: 'en',
    optinNewsLetter: null,
  },
  clientProfileData: null,
  commercialConditionData: null,
  customData: null,
  giftRegistryData: null,
  hooksData: null,
  ignoreProfileData: false,
  invoiceData: null,
  isCheckedIn: false,
  itemMetadata: {
    items: [],
  },
  items: [],
  itemsOrdination: null,
  loggedIn: false,
  marketingData: null,
  messages: [],
  openTextField: null,
  orderFormId: 'test',
  paymentData: {
    availableAccounts: [],
    availableTokens: [],
    giftCardMessages: [],
    giftCards: [],
    installmentOptions: [],
    paymentSystems: [],
    payments: [],
  },
  ratesAndBenefitsData: {
    rateAndBenefitsIdentifiers: [],
    teaser: [],
  },
  salesChannel: '1',
  selectableGifts: [],
  sellers: [],
  shippingData: {
    address: null,
    availableAddresses: [],
    logisticsInfo: [],
    pickupPoints: [],
    selectedAddresses: [],
  },
  storeId: '1',
  storePreferencesData: {
    countryCode: 'BRA',
    currencyCode: 'BRL',
    currencyFormatInfo: {
      currencyDecimalDigits: 2,
      currencyDecimalSeparator: ',',
      currencyGroupSeparator: '.',
      currencyGroupSize: 3,
      startsWithCurrencySymbol: true,
    },
    currencyLocale: 'pt-BR',
    currencySymbol: 'R$',
    saveUserData: false,
    timeZone: 'test',
  },
  subscriptionData: null,
  totalizers: [],
  userProfileId: null,
  userType: null,
  value: 1200,
}
